[project]
name = "aerosim-workspace"
version = "0.1.0"
description = "AeroSim workspace root virtual project"
authors = [
    { name = "Praveen Palanisamy", email = "4770482+praveen-palanisamy@users.noreply.github.com" },
]
dependencies = [
    "aerosim",
    "aerosim-controllers",
    "aerosim-core",
    "aerosim-data",
    "aerosim-dynamics-models",
    "aerosim-scenarios",
    "aerosim-sensors",
    "aerosim-world",
]
readme = "README.md"
requires-python = ">= 3.12"

[tool.uv]
package = false

[tool.uv.workspace]
members = ["aerosim*"]
exclude = ["aerosim-macros", "aerosim-world-link"]

[tool.uv.sources]
aerosim = { workspace = true }
aerosim-controllers = { workspace = true }
aerosim-core = { workspace = true }
aerosim-data = { workspace = true }
aerosim-dynamics-models = { workspace = true }
aerosim-scenarios = { workspace = true }
aerosim-sensors = { workspace = true }
aerosim-world = { workspace = true }

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
    "mkdocs>=1.6.1",
    "mcap==1.2.2",
    "maturin>=1.5,<2.0",
    "black>=25.1.0",
]
