[package]
name = "aerosim-controllers"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aerosim_controllers"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
