[package]
name = "aerosim-scenearios"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aerosim_scenarios"
crate-type = ["cdylib"]

[dependencies]
aerosim-data = { path = "../aerosim-data" }
pyo3.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
